file_format: "1"
id: encodertest
name: EncoderTest
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - encodertest_left
  - encodertest_right
