file_format: "1"
id: epdtest
name: EpaperTest
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [spi_epd]
features:
  - keys:
siblings:
  - epdtest_left
  - epdtest_right
